export const NewsActionTypes = {
  FETCH_NEWS_START: 'FETCH_NEWS_START',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAILURE: 'FETCH_NEWS_FAILURE',
  SET_SELECTED_NEWS: 'SET_SELECTED_NEWS'
};
